#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --partition rtx6000			### specify partition name where to run a job.
#SBATCH --qos azencot
#SBATCH --time 2-00:00:00			### limit the time of job running. Format: D-H:MM:SS
#SBATCH --job-name sp_precond_mr50		### name of the job
#SBATCH --output diffem_spectral_precond-%J.out	### output log for running job - %J for job number

#SBATCH --gpus=1				### number of GPUs

### Print some data to output file ###
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

### Start your src_code below ####
cd "${SLURM_SUBMIT_DIR}" || { echo "cd SLURM_SUBMIT_DIR failed"; exit 1; }
export PYTHONUNBUFFERED=1
module load anaconda
source activate idan2_env
python run_diffem_mmps_spectral_precond.py \
    --config ./configs/seq_len_24/energy.yaml \
    --missing_rate 0.5 \
    --mmps_cg_iters 1 \
    --spectral_n_probes 1 \
    --wandb true \
    --tags "diffem_mmps_spectral_precond" "energy" "50_missing_rate" "iter_stl_init"
