#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --partition rtx6000			### specify partition name where to run a job.
#SBATCH --qos azencot
#SBATCH --time 7-00:00:00			### limit the time of job running. Format: D-H:MM:SS
#SBATCH --job-name ts_noise_01_cg3_anneal	### name of the job
#SBATCH --output ts_noise_01_cg3_anneal-%J.out	### output log for running job - %J for job number

#SBATCH --gpus=1				### number of GPUs

### Print some data to output file ###
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

### Start your src_code below ####
module load anaconda
source activate idan2_env
python run_diffem_mmps_general_corruption.py --config ./configs/seq_len_24/energy.yaml --corruption_type ts_gaussian_noise --corruption_noise_level 0.1 --mmps_cg_iters 3 --sigma_y_anneal --sigma_y_start 0.3 --sigma_y_end 0.1 --wandb true --tags "ts_gaussian_noise" "noise_0.1" "cg3" "anneal" "energy" "seq_len_24"
