#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --partition rtx6000			### specify partition name where to run a job. main: all nodes; gtx1080: 1080 gpu card nodes; rtx2080: 2080 nodes; teslap100: p100 nodes; titanrtx: titan nodes
#SBATCH --qos azencot
##SBATCH --gpus=rtx_6000:1			# 1 GPU
#SBATCH --time 7-00:00:00			### limit the time of job running. Make sure it is not greater than the partition time limit!! Format: D-H:MM:SS
#SBATCH --job-name kalman_cur_dp	### name of the job
#SBATCH --output train-%J.out			### output log for running job - %J for job number
##SBATCH --mail-user=arbivid@post.bgu.ac.il    ### User's email for sending job status
##SBATCH --mail-type=ALL			### conditions for sending the email. ALL,BEGIN,END,FAIL, REQUEU, NONE

#SBATCH --gpus=1				### number of GPUs, allocating more than 1 requires IT team's permission
##SBATCH --mem=32G				### amount of RAM memory, allocating more than 60G requires IT team's permission
##SBATCH --cpus-per-task=6			### number of CPU cores, allocating more than 10G requires IT team's permission

### Print some data to output file ###
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

# Repo root: configs and scripts use paths relative to submit directory.
cd "${SLURM_SUBMIT_DIR}" || { echo "cd SLURM_SUBMIT_DIR failed"; exit 1; }
export PYTHONUNBUFFERED=1

### Start your src_code below ####
module load anaconda    ### load anaconda module (must be present when working with conda environments)
source activate idan2_env    ### activate a conda environment, replace my_env with your conda environment
python run_diffem_mmps_kalman_curriculum_decomp_proj.py --config ./configs/seq_len_24/energy.yaml --missing_rate 0.5 --wandb true --tags "kalman_curriculum_decomp_proj" "energy" "50_missing_rate" "combo_experiment" "kalman_init" "decomposition_estep" "curriculum"
