#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --partition rtx6000			### specify partition name where to run a job.
#SBATCH --qos azencot
#SBATCH --time 7-00:00:00			### limit the time of job running. Format: D-H:MM:SS
#SBATCH --job-name general_missing_50	### name of the job
#SBATCH --output general_missing_50-%J.out	### output log for running job - %J for job number

#SBATCH --gpus=1				### number of GPUs

### Print some data to output file ###
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

### Start your src_code below ####
module load anaconda
source activate idan2_env
python run_diffem_mmps_general_corruption.py --config ./configs/seq_len_24/energy.yaml --corruption_type missing --missing_rate 0.5 --wandb true --tags "general_corruption" "missing" "50_missing_rate" "energy" "seq_len_24"
