#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --partition rtx6000
#SBATCH --qos azencot
#SBATCH --time 7-00:00:00
#SBATCH --job-name diffem_new
#SBATCH --output diffem_new-%J.out

#SBATCH --gpus=1

### Print some data to output file ###
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

### Start your code below ####
module load anaconda
source activate idan2_env

python run_diffem_pure_new.py
