#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
################################################################################################

#SBATCH --partition main
#SBATCH --qos normal
#SBATCH --time 7-00:00:00
#SBATCH --job-name gnoise_energy_syan_ng
#SBATCH --output gnoise_energy_syan_ng-%J.out
#SBATCH --gpus=1

cd "${SLURM_SUBMIT_DIR}" || { echo "cd SLURM_SUBMIT_DIR failed"; exit 1; }
export PYTHONUNBUFFERED=1

echo "$(date)"
echo -e "SLURM_JOBID:\t\t${SLURM_JOBID}"
echo -e "SLURM_JOB_NODELIST:\t${SLURM_JOB_NODELIST}"
echo -e "PWD:\t\t\t$(pwd)"

module load anaconda
source activate idan2_env

python run_diffem_mmps_general_corruption.py \
  --config ./configs/seq_len_24/energy.yaml \
  --corruption_type gaussian_noise \
  --corruption_noise_level 0.1 \
  --sigma_y_anneal \
  --sigma_y_start 0.1 \
  --sigma_y_end 0.01 \
  --wandb true \
  --tags "gaussian_noise" "energy" "sigma0.10" "ablation" "sigma_y_anneal" "seq_len_24"
