#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --partition main			### specify partition name where to run a job.
#SBATCH --qos normal
#SBATCH --time 7-00:00:00			### limit the time of job running.
#SBATCH --job-name kalman_cur		### name of the job
#SBATCH --output kalman_cur-%J.out		### output log for running job - %J for job number

#SBATCH --gpus=1				### number of GPUs

### Print some data to output file ###
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

# Repo root: configs and scripts use paths relative to submit directory.
cd "${SLURM_SUBMIT_DIR}" || { echo "cd SLURM_SUBMIT_DIR failed"; exit 1; }
export PYTHONUNBUFFERED=1

### Start your code below ####
module load anaconda
source activate idan2_env
python run_diffem_mmps_kalman_curriculum.py --config ./configs/seq_len_24/energy.yaml --missing_rate 0.5 --wandb true --tags "kalman_curriculum" "energy" "50_missing_rate" "combo_experiment" "kalman_init" "curriculum"
