#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --partition main
#SBATCH --qos normal
#SBATCH --time 7-00:00:00
#SBATCH --job-name gibbs_decomp
#SBATCH --output gibbs_decomp-%J.out

#SBATCH --gpus=1

### Print some data to output file ###
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

### Start your src_code below ####
module load anaconda
source activate idan2_env
python run_diffem_mmps_gibbs_decomp.py --config ./configs/seq_len_24/energy.yaml --missing_rate 0.5 --gibbs_synthetic_confidence 0.3 --wandb true --tags "diffem_mmps_gibbs_decomp" "energy" "50_missing_rate" "decomposition_estep"
