#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --partition rtx6000			### specify partition name where to run a job.
#SBATCH --qos azencot
#SBATCH --time 3-00:00:00			### limit the time of job running. Format: D-H:MM:SS
#SBATCH --job-name cond_n02		### name of the job
#SBATCH --output cond_n02-%J.out		### output log for running job - %J for job number

#SBATCH --gpus=1				### number of GPUs

### Print some data to output file ###
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

### Start your src_code below ####
module load anaconda
source activate idan2_env
python run_diffem_pure_combined.py \
  --config ./configs/seq_len_24/energy.yaml \
  --corruption_type gaussian_noise \
  --corruption_noise_level 0.2 \
  --missing_rate 0.0 \
  --em_iters 10 \
  --m_step_epochs 100 \
  --e_step_sample_steps 64 \
  --uncond_epochs_per_iter 50 \
  --early_stop_patience 15 \
  --wandb true \
  --tags "pure_cond" "gaussian_noise" "sigma_0.2" "energy" "seq_len_24" "conditional_diffem"
