#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --partition rtx6000			### specify partition name where to run a job.
#SBATCH --qos azencot
#SBATCH --time 7-00:00:00			### limit the time of job running. Format: D-H:MM:SS
#SBATCH --job-name pure_comb_90		### name of the job
#SBATCH --output pure_comb_90-%J.out		### output log for running job - %J for job number

#SBATCH --gpus=1				### number of GPUs

### Print some data to output file ###
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

### Start your src_code below ####
module load anaconda
source activate idan2_env
python run_diffem_pure_combined.py \
  --config ./configs/seq_len_24/energy.yaml \
  --missing_rate 0.9 \
  --em_iters 20 \
  --m_step_epochs 200 \
  --e_step_sample_steps 64 \
  --uncond_epochs_per_iter 200 \
  --ppca_rank 32 \
  --ppca_iters 12 \
  --early_stop_patience 30 \
  --wandb true \
  --tags "pure_combined" "90_missing" "high_budget" "energy" "seq_len_24" "paper_aligned"
