#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --time 2-00:00:00    ### limit the time of job running. Make sure it is not greater than the partition time limit!! Format: D-H:MM:SS
#SBATCH --job-name pe_cor_ettm1
#SBATCH --output /home/galfad/corrupted-data-generation/slurm_logs/%J.out
#SBATCH --error /home/galfad/corrupted-data-generation/slurm_logs/%J.err
#SBATCH --gpus=rtx_4090:1
#SBATCH --partition main
#SBATCH --qos normal
#SBATCH --mem=32G
#SBATCH --cpus-per-task=6

### Print some data to output file ###
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

### Start your src_code below ####
umask 0000    ### ensure log files are created with rwx permissions for all (777)
module load anaconda
source activate /home/galfad/.conda/envs/time_series_nev
export PYTHONNOUSERSITE=1
export LD_LIBRARY_PATH=""
export WANDB_API_KEY="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"

python run_diffem_mmps_periodic_correction.py --config ./configs/seq_len_24/ettm1.yaml --missing_rate 0.7 --wandb true --tags "periodic_correction" "ETTm1" "70_missing_rate" "fix_missing_rates" "seq_len=24" 2>&1
python run_diffem_mmps_periodic_correction.py --config ./configs/seq_len_24/ettm1.yaml --missing_rate 0.5 --wandb true --tags "periodic_correction" "ETTm1" "50_missing_rate" "fix_missing_rates" "seq_len=24" 2>&1
python run_diffem_mmps_periodic_correction.py --config ./configs/seq_len_24/ettm1.yaml --missing_rate 0.3 --wandb true --tags "periodic_correction" "ETTm1" "30_missing_rate" "fix_missing_rates" "seq_len=24" 2>&1

chmod 666 /home/galfad/corrupted-data-generation/slurm_logs/$SLURM_JOBID.out /home/galfad/corrupted-data-generation/slurm_logs/$SLURM_JOBID.err
