#!/bin/bash
#SBATCH --partition rtx6000
#SBATCH --qos azencot
#SBATCH --time 7-00:00:00
#SBATCH --job-name c020_50
#SBATCH --output train-%J.out
#SBATCH --gpus=1

echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

cd "${SLURM_SUBMIT_DIR}" || { echo "cd SLURM_SUBMIT_DIR failed"; exit 1; }
export PYTHONUNBUFFERED=1

### Sensitivity: c=0.2
module load anaconda
source activate idan2_env
python run_diffem_mmps_self_correcting.py \
    --config ./configs/seq_len_24/energy.yaml \
    --missing_rate 0.5 \
    --wandb true \
    --tags "self_correcting_em" "energy" "50_missing_rate" "sensitivity" "c_020" \
    --adaptive_sigma_y \
    --sigma_y_ratio 0.2 \
    --sigma_y_floor 0.01 \
    --mmps_cg_iters 5 \
    --consistency_projection \
    --lambda_obs 0.5 \
    --no_phase3
