#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --partition rtx6000			### specify partition name where to run a job.
#SBATCH --qos azencot
##SBATCH --gpus=rtx_6000:1			# 1 GPU
#SBATCH --time 7-00:00:00			### limit the time of job running.
#SBATCH --job-name cond_eval		### name of the job
#SBATCH --output train-%J.out			### output log for running job - %J for job number
##SBATCH --mail-user=arbivid@post.bgu.ac.il
##SBATCH --mail-type=ALL

#SBATCH --gpus=1				### number of GPUs
##SBATCH --mem=32G
##SBATCH --cpus-per-task=6

### Print some data to output file ###
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

cd "${SLURM_SUBMIT_DIR}" || { echo "cd SLURM_SUBMIT_DIR failed"; exit 1; }
export PYTHONUNBUFFERED=1

### Start your src_code below ####
module load anaconda
source activate idan2_env
python run_diffem_conditional.py \
    --config ./configs/seq_len_24/energy.yaml \
    --missing_rate 0.5 \
    --allow_tf32 \
    --wandb true \
    --tags "diffem_conditional" "energy" "50_missing_rate" "cond_eval" "no_phase3" "tf32" \
    --mmps_sigma_y 0.01 \
    --mmps_cg_iters 1
