#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --partition rtx6000			### specify partition name where to run a job.
#SBATCH --qos azencot
#SBATCH --time 7-00:00:00			### limit the time of job running.
#SBATCH --job-name kal_cur_768		### name of the job
#SBATCH --output kal_cur_768-%J.out		### output log for running job - %J for job number

#SBATCH --gpus=1				### number of GPUs
#SBATCH --mem=64G
#SBATCH --cpus-per-task=8

### Print some data to output file ###
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

# Repo root: configs and scripts use paths relative to submit directory.
cd "${SLURM_SUBMIT_DIR}" || { echo "cd SLURM_SUBMIT_DIR failed"; exit 1; }
export PYTHONUNBUFFERED=1

### Start your code below ####
module load anaconda
source activate idan2_env
python run_diffem_mmps_kalman_curriculum.py --config ./configs/seq_len_768/energy.yaml --missing_rate 0.5 --m_step_epochs 100 --em_iters 15 --e_step_batch_size 8 --kalman_fit_timeout 15 --wandb true --tags "kalman_curriculum" "energy" "50_missing_rate" "seq_len_768" "kalman_init" "curriculum"
