#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --time 7-00:00:00
#SBATCH --job-name our_ettm1_seq96_mr30_50_70
#SBATCH --output /home/galfad/corrupted-data-generation/slurm_logs/%J.out
#SBATCH --error /home/galfad/corrupted-data-generation/slurm_logs/%J.err
#SBATCH --gpus=rtx_4090:1
#SBATCH --partition main
#SBATCH --qos normal
#SBATCH --mem=32G
#SBATCH --cpus-per-task=6

echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

umask 0000
module load anaconda
source activate /home/galfad/.conda/envs/time_series_nev
export PYTHONNOUSERSITE=1
export LD_LIBRARY_PATH=""
export RECON_CACHE_DIR="./recon_cache_our_ettm1_seq96"
mkdir -p "$RECON_CACHE_DIR"
chmod 777 "$RECON_CACHE_DIR"
export WANDB_API_KEY="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"

# python run_co_evolving_em.py --stl_n_iters 1 --config ./configs/seq_len_96/ettm1.yaml --missing_rate 0.3 --method our --corruption_type missing_observation --missing_type fix_missing_rates --recon_cache_dir "$RECON_CACHE_DIR" --wandb true --tags "our" "missing_observation" "fix_missing_rates" "ETTm1" "30_missing_rate" "seq_len=96" 2>&1
# python run_co_evolving_em.py --stl_n_iters 1 --config ./configs/seq_len_96/ettm1.yaml --missing_rate 0.5 --method our --corruption_type missing_observation --missing_type fix_missing_rates --recon_cache_dir "$RECON_CACHE_DIR" --wandb true --tags "our" "missing_observation" "fix_missing_rates" "ETTm1" "50_missing_rate" "seq_len=96" 2>&1
python run_co_evolving_em.py --stl_n_iters 1 --config ./configs/seq_len_96/ettm1.yaml --missing_rate 0.7 --method our --corruption_type missing_observation --missing_type fix_missing_rates --recon_cache_dir "$RECON_CACHE_DIR" --wandb true --tags "our" "missing_observation" "fix_missing_rates" "ETTm1" "70_missing_rate" "seq_len=96" 2>&1

chmod 666 /home/galfad/corrupted-data-generation/slurm_logs/$SLURM_JOBID.out /home/galfad/corrupted-data-generation/slurm_logs/$SLURM_JOBID.err
